apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mediflow-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: mediflow.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mediflow-frontend
                port:
                  number: 80
